name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  base:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update PATH
        run: echo "$HOME/.local/share/lemon/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf python3 python3-pip ninja-build qemu-utils nasm
          sudo python3 -m pip install meson

      - name: Initialize and Update submodules
        run: git submodule update --init

      - name: Get hash of latest llvm-project commit
        run: |
          git ls-remote https://github.com/LemonOSProject/llvm-project.git | head -1 > llvm-hash.txt
          echo "Commit Hash:"
          cat llvm-hash.txt

      - name: Cache the toolchain and sysroot
        uses: actions/cache@v2
        with:
          path: |
            **/Toolchain/
            !**/Toolchain/*.sh
            !**/Toolchain/*.patch
          key: ${{ runner.os }}-lemon-toolchain-${{ hashFiles('**/Toolchain/buildtoolchain.sh') }}-${{ hashFiles('llvm-hash.txt') }}-${{ hashFiles('**/Toolchain/lemon-binutils-2.32.patch') }}
          restore-keys: |
            ${{ runner.os }}-lemon-toolchain-${{ hashFiles('**/Toolchain/buildtoolchain.sh') }}-${{ hashFiles('llvm-hash.txt') }}-${{ hashFiles('**/Toolchain/lemon-binutils-2.32.patch') }}

      - name: Build the toolchain
        run: Toolchain/buildtoolchain.sh build

      - name: Configure dependencies
        run: Scripts/configure.sh
        
      - name: Building system
        run: ninja -C Build install

      - name: Building disk image
        run: |
          ninja -C Build disk
  full-system:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update PATH
        run: echo "$HOME/.local/share/lemon/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf python3 python3-pip ninja-build qemu-utils nasm
          sudo python3 -m pip install meson

      - name: Initialize and Update submodules
        run: git submodule update --init

      - name: Get hash of latest llvm-project commit
        run: |
          git ls-remote https://github.com/LemonOSProject/llvm-project.git | head -1 > llvm-hash.txt
          echo "Commit Hash:"
          cat llvm-hash.txt

      - name: Cache the toolchain and sysroot
        uses: actions/cache@v2
        with:
          path: |
            **/Toolchain/
            !**/Toolchain/*.sh
            !**/Toolchain/*.patch
          key: ${{ runner.os }}-lemon-toolchain-${{ hashFiles('**/Toolchain/buildtoolchain.sh') }}-${{ hashFiles('llvm-hash.txt') }}-${{ hashFiles('**/Toolchain/lemon-binutils-2.32.patch') }}
          restore-keys: |
            ${{ runner.os }}-lemon-toolchain-${{ hashFiles('**/Toolchain/buildtoolchain.sh') }}-${{ hashFiles('llvm-hash.txt') }}-${{ hashFiles('**/Toolchain/lemon-binutils-2.32.patch') }}
            
      - name: Build the toolchain
        run: Toolchain/buildtoolchain.sh build

      - name: Configure dependencies
        run: Scripts/configure.sh

      - name: Cache the LLVM port
        uses: actions/cache@v2
        with:
          path: |
            **/Ports/llvm-project
          key: ${{ runner.os }}-lemon-llvm-${{ hashFiles('~/llvm-hash.txt') }}-${{ hashFiles('**/Ports/llvm.sh') }}
          restore-keys: |
            ${{ runner.os }}-lemon-llvm-
            ${{ runner.os }}-lemon-llvm-${{ hashFiles('~/llvm-hash.txt') }}-
            ${{ runner.os }}-lemon-llvm-${{ hashFiles('~/llvm-hash.txt') }}-${{ hashFiles('**/Ports/llvm.sh') }}

      - name: Cache the Python port
        uses: actions/cache@v2
        with:
          path: |
            **/Ports/Python*
          key: ${{ runner.os }}-lemon-python-${{ hashFiles('**/Ports/lemon-Python*.patch') }}-${{ hashFiles('**/Ports/python.sh') }}
          restore-keys: |
            ${{ runner.os }}-lemon-python-${{ hashFiles('**/Ports/lemon-Python*.patch') }}-${{ hashFiles('**/Ports/python.sh') }}

      - name: Building system
        run: ninja -C Build install

      - name: Build extra ports
        run: |
          Ports/buildport.sh doom
          Ports/buildport.sh nyancat
          Ports/buildport.sh nasm
          Ports/buildport.sh lemon-binutils
          Ports/buildport.sh llvm
          Ports/buildport.sh python
          Ports/buildport.sh curl
          Ports/buildport.sh busybox

      - name: Building disk image
        run: ninja -C Build disk
      
      - name: Uploading image as artefact
        uses: actions/upload-artifact@v2
        with:
          name: Lemon
          path: Disks/Lemon.img
